### ISSUE TITLE
Route::inertia unusable on other models

### ISSUE THREAD

**Issue by Cyborgmatt** [Harmonic/inertia-table#4]
Due to the way [InertiaTableServiceProvider](https://github.com/Harmonic/inertia-table/blob/master/src/InertiaTableServiceProvider.php) handles the route creation, the feature only works for the user model as the URLs are hard coded with {user} variables.

See the events routing below which uses Route::inertia

<img width="1134" alt="RouteIssue" src="https://user-images.githubusercontent.com/3114217/61528238-264b9200-aa16-11e9-84a4-6136f428d473.png">

**Comment by craigharman** [comment]
Thanks Matthew, we haven't go to the CRUD routes yet, only the table display but that's next on the list.

**Comment by craigharman** [comment]
Fixed in #6

**Comment by craigharman** [comment]
Fixed in release https://github.com/Harmonic/inertia-table/releases/tag/v1.0.3
