### ISSUE TITLE
Soft Delete results in 404 Error

### ISSUE THREAD

**Issue by Cyborgmatt** [Harmonic/inertia-table#5]
Due to the following function being missing from the models, when you try and edit a model that has been soft deleted you will get a 404 error.

    public function resolveRouteBinding($value)
    {
        return $this->where('id', $value)->withTrashed()->first() ?? abort(404);
    }

**Comment by craigharman** [comment]
Fixed in commit https://github.com/Harmonic/inertia-table/commit/878490c10c6ecd77578e14d56fe521afd5cb2453

Will add to next release.

**Comment by craigharman** [comment]
Fixed in release https://github.com/Harmonic/inertia-table/releases/tag/v1.0.3
