### ISSUE TITLE
Route::inertia conflict

### ISSUE THREAD

**Issue by pakka63** [Harmonic/inertia-table#8]
Hi,
The macro 
`Route::macro('inertia', function ($routeName){...});` 
now conflict with the last changes in the  inertiajs/inertia-laravel project where now exist the same macro name but with different parameters in the closure.
I suggest to modify the name with a new one like 'inertiaTable'
Bye
 Pakka

**Comment by craigharman** [comment]
Thank you for the issue report. I have modified in #9
